services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - expense_tracker_db:/var/lib/postgresql

volumes:
  expense_tracker_db:
