[build]
buildCommand = "pnpm --filter @expense-tracker/job build"
watchPatterns = ["apps/job/src/**"]

[deploy]
startCommand = "node apps/job/dist/index.js"
cronSchedule = "0 0 * * *"
restartPolicyType = "NEVER"
