/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDashboardProfileRouteImport } from './routes/_app.dashboard.profile'
import { Route as AppDashboardTransactionsIndexRouteImport } from './routes/_app.dashboard.transactions.index'
import { Route as AppDashboardRecurringIndexRouteImport } from './routes/_app.dashboard.recurring.index'
import { Route as AppDashboardProductsIndexRouteImport } from './routes/_app.dashboard.products.index'
import { Route as AppDashboardTransactionsIdRouteImport } from './routes/_app.dashboard.transactions.$id'
import { Route as AppDashboardRecurringNewRouteImport } from './routes/_app.dashboard.recurring.new'
import { Route as AppDashboardRecurringIdRouteImport } from './routes/_app.dashboard.recurring.$id'
import { Route as AppDashboardProductsNewRouteImport } from './routes/_app.dashboard.products.new'
import { Route as AppDashboardProductsProductIdRouteImport } from './routes/_app.dashboard.products.$productId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardProfileRoute = AppDashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardTransactionsIndexRoute =
  AppDashboardTransactionsIndexRouteImport.update({
    id: '/dashboard/transactions/',
    path: '/dashboard/transactions/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardRecurringIndexRoute =
  AppDashboardRecurringIndexRouteImport.update({
    id: '/dashboard/recurring/',
    path: '/dashboard/recurring/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardProductsIndexRoute =
  AppDashboardProductsIndexRouteImport.update({
    id: '/dashboard/products/',
    path: '/dashboard/products/',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardTransactionsIdRoute =
  AppDashboardTransactionsIdRouteImport.update({
    id: '/dashboard/transactions/$id',
    path: '/dashboard/transactions/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardRecurringNewRoute =
  AppDashboardRecurringNewRouteImport.update({
    id: '/dashboard/recurring/new',
    path: '/dashboard/recurring/new',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardRecurringIdRoute = AppDashboardRecurringIdRouteImport.update({
  id: '/dashboard/recurring/$id',
  path: '/dashboard/recurring/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardProductsNewRoute = AppDashboardProductsNewRouteImport.update({
  id: '/dashboard/products/new',
  path: '/dashboard/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardProductsProductIdRoute =
  AppDashboardProductsProductIdRouteImport.update({
    id: '/dashboard/products/$productId',
    path: '/dashboard/products/$productId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard/profile': typeof AppDashboardProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/products/$productId': typeof AppDashboardProductsProductIdRoute
  '/dashboard/products/new': typeof AppDashboardProductsNewRoute
  '/dashboard/recurring/$id': typeof AppDashboardRecurringIdRoute
  '/dashboard/recurring/new': typeof AppDashboardRecurringNewRoute
  '/dashboard/transactions/$id': typeof AppDashboardTransactionsIdRoute
  '/dashboard/products/': typeof AppDashboardProductsIndexRoute
  '/dashboard/recurring/': typeof AppDashboardRecurringIndexRoute
  '/dashboard/transactions/': typeof AppDashboardTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/dashboard/profile': typeof AppDashboardProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/dashboard/products/$productId': typeof AppDashboardProductsProductIdRoute
  '/dashboard/products/new': typeof AppDashboardProductsNewRoute
  '/dashboard/recurring/$id': typeof AppDashboardRecurringIdRoute
  '/dashboard/recurring/new': typeof AppDashboardRecurringNewRoute
  '/dashboard/transactions/$id': typeof AppDashboardTransactionsIdRoute
  '/dashboard/products': typeof AppDashboardProductsIndexRoute
  '/dashboard/recurring': typeof AppDashboardRecurringIndexRoute
  '/dashboard/transactions': typeof AppDashboardTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/dashboard/profile': typeof AppDashboardProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/products/$productId': typeof AppDashboardProductsProductIdRoute
  '/_app/dashboard/products/new': typeof AppDashboardProductsNewRoute
  '/_app/dashboard/recurring/$id': typeof AppDashboardRecurringIdRoute
  '/_app/dashboard/recurring/new': typeof AppDashboardRecurringNewRoute
  '/_app/dashboard/transactions/$id': typeof AppDashboardTransactionsIdRoute
  '/_app/dashboard/products/': typeof AppDashboardProductsIndexRoute
  '/_app/dashboard/recurring/': typeof AppDashboardRecurringIndexRoute
  '/_app/dashboard/transactions/': typeof AppDashboardTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/profile'
    | '/api/auth/$'
    | '/dashboard/'
    | '/dashboard/products/$productId'
    | '/dashboard/products/new'
    | '/dashboard/recurring/$id'
    | '/dashboard/recurring/new'
    | '/dashboard/transactions/$id'
    | '/dashboard/products/'
    | '/dashboard/recurring/'
    | '/dashboard/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/profile'
    | '/api/auth/$'
    | '/dashboard'
    | '/dashboard/products/$productId'
    | '/dashboard/products/new'
    | '/dashboard/recurring/$id'
    | '/dashboard/recurring/new'
    | '/dashboard/transactions/$id'
    | '/dashboard/products'
    | '/dashboard/recurring'
    | '/dashboard/transactions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_app/dashboard/profile'
    | '/api/auth/$'
    | '/_app/dashboard/'
    | '/_app/dashboard/products/$productId'
    | '/_app/dashboard/products/new'
    | '/_app/dashboard/recurring/$id'
    | '/_app/dashboard/recurring/new'
    | '/_app/dashboard/transactions/$id'
    | '/_app/dashboard/products/'
    | '/_app/dashboard/recurring/'
    | '/_app/dashboard/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/profile': {
      id: '/_app/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AppDashboardProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/transactions/': {
      id: '/_app/dashboard/transactions/'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions/'
      preLoaderRoute: typeof AppDashboardTransactionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/recurring/': {
      id: '/_app/dashboard/recurring/'
      path: '/dashboard/recurring'
      fullPath: '/dashboard/recurring/'
      preLoaderRoute: typeof AppDashboardRecurringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/products/': {
      id: '/_app/dashboard/products/'
      path: '/dashboard/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof AppDashboardProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/transactions/$id': {
      id: '/_app/dashboard/transactions/$id'
      path: '/dashboard/transactions/$id'
      fullPath: '/dashboard/transactions/$id'
      preLoaderRoute: typeof AppDashboardTransactionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/recurring/new': {
      id: '/_app/dashboard/recurring/new'
      path: '/dashboard/recurring/new'
      fullPath: '/dashboard/recurring/new'
      preLoaderRoute: typeof AppDashboardRecurringNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/recurring/$id': {
      id: '/_app/dashboard/recurring/$id'
      path: '/dashboard/recurring/$id'
      fullPath: '/dashboard/recurring/$id'
      preLoaderRoute: typeof AppDashboardRecurringIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/products/new': {
      id: '/_app/dashboard/products/new'
      path: '/dashboard/products/new'
      fullPath: '/dashboard/products/new'
      preLoaderRoute: typeof AppDashboardProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/products/$productId': {
      id: '/_app/dashboard/products/$productId'
      path: '/dashboard/products/$productId'
      fullPath: '/dashboard/products/$productId'
      preLoaderRoute: typeof AppDashboardProductsProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardProfileRoute: typeof AppDashboardProfileRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardProductsProductIdRoute: typeof AppDashboardProductsProductIdRoute
  AppDashboardProductsNewRoute: typeof AppDashboardProductsNewRoute
  AppDashboardRecurringIdRoute: typeof AppDashboardRecurringIdRoute
  AppDashboardRecurringNewRoute: typeof AppDashboardRecurringNewRoute
  AppDashboardTransactionsIdRoute: typeof AppDashboardTransactionsIdRoute
  AppDashboardProductsIndexRoute: typeof AppDashboardProductsIndexRoute
  AppDashboardRecurringIndexRoute: typeof AppDashboardRecurringIndexRoute
  AppDashboardTransactionsIndexRoute: typeof AppDashboardTransactionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardProfileRoute: AppDashboardProfileRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardProductsProductIdRoute: AppDashboardProductsProductIdRoute,
  AppDashboardProductsNewRoute: AppDashboardProductsNewRoute,
  AppDashboardRecurringIdRoute: AppDashboardRecurringIdRoute,
  AppDashboardRecurringNewRoute: AppDashboardRecurringNewRoute,
  AppDashboardTransactionsIdRoute: AppDashboardTransactionsIdRoute,
  AppDashboardProductsIndexRoute: AppDashboardProductsIndexRoute,
  AppDashboardRecurringIndexRoute: AppDashboardRecurringIndexRoute,
  AppDashboardTransactionsIndexRoute: AppDashboardTransactionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
